[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { workspace = true }
leptos_router = { workspace = true }
leptos_meta = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
shared = { path = "../shared" }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
tracing = { workspace = true }
time = "0.3.36"
leptonic = { git = "https://github.com/lpotthast/leptonic", branch = "migrate-to-leptos-0.7" }
leptonic-theme = { git = "https://github.com/lpotthast/leptonic", branch = "migrate-to-leptos-0.7" }
icondata = "0.4"
gloo-net = "0.6"
sqlx = { workspace = true, optional = true }
bcrypt = { version = "0.15", optional = true }
axum-extra = { workspace = true, optional = true }

[features]
hydrate = ["leptos/hydrate", "leptonic/hydrate"]
ssr = [
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "leptonic/ssr",
  "dep:sqlx",
  "dep:bcrypt",
  "dep:axum-extra",
]
