[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { workspace = true, features = ["csr"] }
leptos_router = { workspace = true, features = ["csr"] }
leptos_meta = { workspace = true, features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
shared = { path = "../shared" }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
tracing = { workspace = true }

[features]
hydrate = ["leptos/hydrate", "leptos_meta/hydrate", "leptos_router/hydrate"]
ssr = ["leptos/ssr", "leptos_meta/ssr", "leptos_router/ssr"]
